version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile for Spring Boot app
    ports:
      - "8080:8080"
    networks:
      - app-network

    depends_on:
      - mysql

  frontend:
    build:
      context: ./src/main/webapp/reactjs
      dockerfile: Dockerfile  # Dockerfile for React app
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

  mysql:
    image: mysql@sha256:fd8d1b4e287c49e1e35eb5a103f337111947662130eb8a3e6c3e823813f47f7d
    environment:
      MYSQL_ROOT_PASSWORD : 123456789
      MYSQL_DATABASE: SpringRest
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
